version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
      - aws s3 cp s3://my-local-maven-repo/snapshot/ORM/target/orm-0.1.jar ~/.m2/repository/com/revature/orm/0.1/orm-0.1.jar
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/p1-1.war
